import React from 'react';
import { motion } from 'motion/react';
import { Sparkles, TrendingUp, AlertTriangle, Lightbulb } from 'lucide-react';

const MotionDiv = motion.div as any;

interface Insight {
  type: 'opportunity' | 'risk' | 'trend' | 'tip';
  title: string;
  description: string;
}

export const AIInsights: React.FC<{ locationName: string; score: number; businessType: string }> = ({ locationName, score, businessType }) => {
  // Simulated AI insights (replace with real API call later)
  const insights: Insight[] = [
    {
      type: 'opportunity',
      title: 'Peak Hours Opportunity',
      description: 'Foot traffic peaks 2-4pm but competitor lines are long. Consider express ordering to capture overflow demand.'
    },
    {
      type: 'trend',
      title: 'Demographic Shift',
      description: `Gen Z population in ${locationName} increased 23% YoY. Strong alignment with ${businessType.toLowerCase()} demand - market is expanding.`
    },
    {
      type: 'risk',
      title: 'Rent Escalation',
      description: 'Commercial rents in this zone increased 12% annually. Budget for 3-5% annual increases in lease renewals.'
    },
    {
      type: 'tip',
      title: 'Competitive Edge',
      description: 'No competitors offer late-night service past 8pm. Extended hours (until 10pm) could capture 15-20% additional revenue.'
    }
  ];

  // Add score-specific insights
  if (score >= 95) {
    insights.unshift({
      type: 'opportunity',
      title: 'Elite Location Match',
      description: 'This location scores in the top 5% for your business type. High probability of success with proper execution.'
    });
  }

  const icons = {
    opportunity: TrendingUp,
    risk: AlertTriangle,
    trend: Sparkles,
    tip: Lightbulb
  };

  const colors = {
    opportunity: { bg: 'bg-emerald-50 dark:bg-emerald-500/10', border: 'border-emerald-200 dark:border-emerald-500/30', text: 'text-emerald-700 dark:text-emerald-400', icon: 'text-emerald-600 dark:text-emerald-400' },
    risk: { bg: 'bg-orange-50 dark:bg-orange-500/10', border: 'border-orange-200 dark:border-orange-500/30', text: 'text-orange-700 dark:text-orange-400', icon: 'text-orange-600 dark:text-orange-400' },
    trend: { bg: 'bg-amber-50 dark:bg-amber-500/10', border: 'border-amber-200 dark:border-amber-500/30', text: 'text-amber-700 dark:text-amber-400', icon: 'text-amber-600 dark:text-amber-400' },
    tip: { bg: 'bg-violet-50 dark:bg-violet-500/10', border: 'border-violet-200 dark:border-violet-500/30', text: 'text-violet-700 dark:text-violet-400', icon: 'text-violet-600 dark:text-violet-400' }
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 mb-4">
        <Sparkles className="w-5 h-5 text-violet-600 dark:text-violet-400" />
        <h3 className="font-bold text-slate-900 dark:text-white">AI Insights for {locationName}</h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        {insights.map((insight, idx) => {
          const Icon = icons[insight.type];
          const color = colors[insight.type];

          return (
            <MotionDiv
              key={idx}
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: idx * 0.1 }}
              whileHover={{ scale: 1.02, x: 4 }}
              className={`p-4 border ${color.border} ${color.bg} rounded-xl hover:shadow-md cursor-pointer transition-all`}
            >
              <div className="flex items-start gap-3">
                <div className={`p-2 bg-white dark:bg-slate-700 rounded-lg ${color.icon} flex-shrink-0`}>
                  <Icon className="w-4 h-4" />
                </div>
                <div className="flex-1 min-w-0">
                  <div className={`text-sm font-bold ${color.text} mb-1 break-words`}>
                    {insight.title}
                  </div>
                  <div className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed break-words">
                    {insight.description}
                  </div>
                </div>
              </div>
            </MotionDiv>
          );
        })}
      </div>

      <div className="mt-4 pt-4 border-t border-slate-200 dark:border-slate-700">
        <p className="text-xs text-slate-500 dark:text-slate-400">
          💡 Insights generated by Vantage AI using real-time data analysis
        </p>
      </div>
    </div>
  );
};
